### ISSUE TITLE
Step by Step build instruction (Static linked PhantomJS) (Windows)

### ISSUE THREAD

**Issue by JoeyLi-1** [ariya/phantomjs#15018]
Environment: Win10 Pro/ VS2015/ VS2017
Hardware: i5/8G/256G SSD
At least 7-9hours build time; (Only release, could doubled or even more if you build both release and debug)

Phantomjs(master), Webkit(qtwebkit-stable). (32bit)

**Note: All the path below is my local path, you need to use your own local path instead**

## Static linked openssl

1. git clone https://github.com/openssl/openssl.git   
2. checkout OpenSSL_1_0_2-stable (pay attention to the version, must be this branch)
3. perl Configure VC-WIN32 no-shared no-asm --prefix=c:\openssl --openssldir=c:\openssl  
4. follow instruction of install.w32

## Static linked icu
build static linked ICU and replace icu files under (webkit\WebKitLibraries\win\lib32) (rename sicu*.lib to icu*.lib and replace) (seems both icu4c-57 and icu4c-58 works)

## Build static linked QT 5.7.1

1. install vs2015 and vs2017 and install items 1-9 (https://webkit.org/webkit-on-windows/) and add these items` path to ENV path;
2. download http://download.qt.io/official_releases/qt/5.7/5.7.1/single/qt-everywhere-opensource-src-5.7.1.7z and Expand archive to folder A(C:\Qt\static\5.7.1\src\qt-everywhere-opensource-src-5.7.1);
3. open vs2015 x86 native tools command prompt && cd folder A && configure.bat -static -release -platform win32-msvc2015 -prefix C:\Qt\Static\5.7.1-msvc\ -qt-pcre -no-libpng -no-libjpeg -no-freetype -opengl desktop -no-sql-sqlite -openssl -I C:\openssl\include\ -L C:\openssl\lib\  -opensource -confirm-license -make libs -nomake tools -nomake examples -nomake tests -no-cups -no-evdev -no-qml-debug
4. nmake 
5. nmake install

**Note: if you changed any configure params above, you need to clean folder and run config again; Run config not on a clean folder could lead to lots of unexpected errors. So, it is a good idea to create another folder and run config under that folder. In that case, you just delete all the content in that folder and run config again is okay. Unzip QT source files need 10 mins at least.**

## Build static linked webkit

1. Since the repo is huge add(git config --global http.postBuffer 524288000) before git clone; (https://github.com/annulen/webkit)
2. set WEBKIT_OUTPUTDIR=C:\Code\GitHub\webkit-output
3. cd webkit folder and perl Tools/Scripts/build-webkit --qt --release --only-webkit --no-device-orientation --no-web-audio --no-video --no-video-track --no-touch-events --no-touch-slider --no-geolocation --no-xslt --no-netscape-plugin-api --cmakeargs="-Wno-dev -DCMAKE_PREFIX_PATH=\"C:\Qt\static\5.7.1-msvc\" -G \"Visual Studio 14 2015\""
4. open webkit.sln under WEBKIT_OUTPUTDIR with vs2017 and build (encountered issues before with vs2015, but you could try to build with vs2015.)

You might encounter some errors: 
- missing include files: add (C:\Qt\static\5.7-msvc\include) to different *.vcxproj files;
- 	unresolved external symbol: check and update related *.lib files under (webkit\WebKitLibraries\win\lib32) (refer to https://github.com/annulen/webkit/issues/432)
- Change webcore.lib -> libwebcore.lib, (libbrotli, libJavaScriptCore, libwoff2, libWTF)

## Build static linked Phantomjs

1. set WEB_INSPECTOR_RESOURCES_DIR=C:\Code\GitHub\webkit-static\Release\DerivedSources\WebInspectorUI (refer to https://github.com/ariya/phantomjs/issues/14637)
2. add related lib to src\phantomjs.pro e.g. (LIBS += C:/Code/GitHub/phantomjs/common/icudt.lib) I added these libs (icudt/icuin/icuio/icutest/icutu/icuuc/libjpeg/libpng/libxml2/libxslt/sqlite3/zlib/ANGLESupport);
3. open qt creator and add new build qt to build kit, and then build; (refer to https://forum.qt.io/topic/34521/static-compilation-of-qt-5-1-1-on-windows-7-64-bit-with-mingw32/2)

**Comment by JoeyLi-1** [comment]
Build process is nightmare, you need to start over again and again. I might build with QT 5.5.1 again later. If there are any new issues, I will post it here and change the instruction. Hope it could help other beginners.
@annulen @Vitallium helps me a lot in these days. Thank you very much! :)

**Comment by annulen** [comment]
@JoeyLi-1 

* Using Qt 5.5.1 is pointless. If you use old QtWebKit, you loose compatibility with modern web content. If you build new QtWebKit with Qt 5.5.1, you loose lots of bug fixes in Qt
* If static build is too hard for you, why not just use shared build?

**Comment by JoeyLi-1** [comment]
@annulen 

- Use 5.5.1 just because there is warning in QT creator said only support 5.5.1, so I think it may worth to try to build with that version. If you said so, then I will not try that.

- Yes, shared build is quite easy. My project rely on another project which use static linked phantomjs, so I have to build a static linked one by myself to fix some bugs.

**Comment by annulen** [comment]
I have no idea what project prints "Project ERROR: This program can only be compiled with Qt 5.5.x.". Probably it's coming from one of your projects

**Comment by JoeyLi-1** [comment]
That is because I tried to build phantomjs 2.1. After "git checkout remotes/origin/2.1".
In phantomjs.pro:

> if(!equals(QT_MAJOR_VERSION, 5)|!equals(QT_MINOR_VERSION, 5)) {
>     error("This program can only be compiled with Qt 5.5.x.")
> }

**Comment by Vitallium** [comment]
@JoeyLi-1 use `master` instead of branch `2.1`

**Comment by JoeyLi-1** [comment]
@Vitallium Okay, already did.
PDF generated by phantomjs 2.5 development:
![image](https://cloud.githubusercontent.com/assets/20162464/26822605/39ad0d50-4add-11e7-8e46-ba4978e2ac51.png)
PDF generated by phantomjs 2.1.1:
![image](https://cloud.githubusercontent.com/assets/20162464/26822645/5b96e350-4add-11e7-8e35-393834eff731.png)
I am investigating why the output is different. 
And....
How can I get rid of this error "SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)""?

Can you give me some suggestions? Thank you!

**Comment by Vitallium** [comment]
>How can I get rid of this error "SetProcessDpiAwareness failed: "COM error 0x80070005 (Unknown error 0x0ffffffff80070005)""?
Switch to Qt 5.7

**Comment by JoeyLi-1** [comment]
@Vitallium I had built the project with static linked qt 5.7.0.(built by myself with qt-everywhere-opensource-src-5.7.0)
Switch to 5.7.1?

**Comment by Vitallium** [comment]
Yes

**Comment by JoeyLi-1** [comment]
@Vitallium, already switch to 5.7.1, still encountered the "COM error" issue.
Working on debugging.

**Comment by JoeyLi-1** [comment]
@Vitallium Double checked my environment, 5.7.1 works.  Thank you! :)

**Comment by hoangbekey** [comment]
hello, can you send me a static build of qtwebkit. I can't build. I am using qt 5.7.1 static library
Thanks and rear weights

**Comment by hoangbekey** [comment]
> Đúng. Nếu bạn vẫn thấy lỗi này, thì bạn phải gỡ lỗi nó.

hello, can you send me a static build of qtwebkit. I can't build. I am using qt 5.7.1 static library
Thanks and rear weights

**Comment by JoeyLi-1** [comment]
> > Đúng. Nếu bạn vẫn thấy lỗi này, thì bạn phải gỡ lỗi nó.
> 
> hello, can you send me a static build of qtwebkit. I can't build. I am using qt 5.7.1 static library Thanks and rear weights

Sorry bro, can`t help! It is 5 years ago. Did not work on these things for quite a long time. Good luck! @hoangbekey
