### ISSUE TITLE
can't build from source (2.0)

### ISSUE THREAD

**Issue by craveica** [ariya/phantomjs#13265]
g++ -fdebug-types-section -Wl,-O1 -Wl,-z,relro -Wl,-rpath,/home/rav/phantomjs/src/qt/qtwebkit/lib -o ../../bin/jsc .obj/jsc.o   -Wl,-whole-archive -lJavaScriptCore -Wl,-no-whole-archive -L/home/rav/phantomjs/src/qt/qtwebkit/Source/JavaScriptCore/ -Wl,-whole-archive -lWTF -Wl,-no-whole-archive -L/home/rav/phantomjs/src/qt/qtwebkit/Source/WTF/ -licui18n -licuuc -licudata -lQt5Core -lpthread
/home/rav/phantomjs/src/qt/qtwebkit/Source/JavaScriptCore//.obj/runtime/JSArray.o: In function `JSC::JSArray::push(JSC::ExecState*, JSC::JSValue)':
/home/rav/phantomjs/src/qt/qtwebkit/Source/JavaScriptCore/runtime/JSArray.cpp:584: undefined reference to `void JSC::JSObject::putByIndexBeyondVectorLengthWithoutAttributes<(unsigned char)20>(JSC::ExecState*, unsigned int, JSC::JSValue)'
collect2: error: ld returned 1 exit status
Makefile.jsc:98: recipe for target '../../bin/jsc' failed
make[2]: *** [../../bin/jsc] Error 1
make[2]: Leaving directory '/home/rav/phantomjs/src/qt/qtwebkit/Source/JavaScriptCore'
Makefile.JavaScriptCore:126: recipe for target 'sub-jsc-pro-make_first-ordered' failed
make[1]: *** [sub-jsc-pro-make_first-ordered] Error 2
make[1]: Leaving directory '/home/rav/phantomjs/src/qt/qtwebkit/Source/JavaScriptCore'
Makefile:93: recipe for target 'sub-Source-JavaScriptCore-JavaScriptCore-pro-make_first-ordered' failed
make: *** [sub-Source-JavaScriptCore-JavaScriptCore-pro-make_first-ordered] Error 2

**Comment by Vitallium** [comment]
Distro? GCC version?

**Comment by craveica** [comment]
Fedora 22, gcc (GCC) 5.1.1 20150422 (Red Hat 5.1.1-1)

**Comment by Vitallium** [comment]
We don't support GCC 5 atm. I suggest you to use GCC >= 4.7

**Comment by josephagoss** [comment]
@Vitallium I've got build errors with gcc version 4.8. Is 4.7 recommended or a must?

**Comment by felixonmars** [comment]
FYI, the patch on the Qt bug trackers fixes the build for me, on Arch Linux with gcc 5.1.0:
https://bugreports.qt.io/browse/QTBUG-44829

**Comment by craveica** [comment]
Thanks. 
That patch fixed the build with gcc 5.1.1 for me too.

**Comment by sincerefly** [comment]
@felixonmars Thx, That patch fixed the build with gcc 5.1.1 for me too.

https://codereview.qt-project.org/#/c/107921/3/Source/JavaScriptCore/runtime/JSObject.cpp

**Comment by craveica** [comment]
This is no longer an issue as a patch exists.
