### ISSUE TITLE
phantomjs 2.0 fails to build on ubuntu 14.04

### ISSUE THREAD

**Issue by a1gucis** [ariya/phantomjs#12938]
Hi,

I followed the phantomjs 2.0 build procedure on http://phantomjs.org/build.html.
The build fails with:
```
/app/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_InspectorBackendCommands.o): In function `qInitResources_InspectorBackendCommands()':
qrc_InspectorBackendCommands.cpp:(.text._Z39qInitResources_InspectorBackendCommandsv+0x0): multiple definition of `qInitResources_InspectorBackendCommands()'
qrc_InspectorBackendCommands.o:qrc_InspectorBackendCommands.cpp:(.text+0x20): first defined here
/app/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_InspectorBackendCommands.o): In function `qCleanupResources_InspectorBackendCommands()':
qrc_InspectorBackendCommands.cpp:(.text._Z42qCleanupResources_InspectorBackendCommandsv+0x0): multiple definition of `qCleanupResources_InspectorBackendCommands()'
qrc_InspectorBackendCommands.o:qrc_InspectorBackendCommands.cpp:(.text+0x50): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [../bin/phantomjs] Error 1
make[1]: Leaving directory `/app/phantomjs/src'
make: *** [sub-src-phantomjs-pro-make_first-ordered] Error 2
```
Does anyone have any ideas why the compilation/linking process fails?

**Comment by ariya** [comment]
Try to build from the source tarball while we're investigating the issue.

**Comment by Vitallium** [comment]
This issue has been fixed in #12899

**Comment by sumanranjanpanda** [comment]
Hi, 

Yesterday I have tried to install the phantomjs 2.0 build as per the steps on http://phantomjs.org/build.html on my Ubuntu 14.04.

But, it didn't work and failed with the same issue:

	qrc_WebKit.o:qrc_WebKit.cpp:(.text+0x90): first defined here
	/usr/local/share/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_InspectorBackendCommands.o): In function `qInitResources_InspectorBackendCommands()':
	qrc_InspectorBackendCommands.cpp:(.text._Z39qInitResources_InspectorBackendCommandsv+0x0): multiple definition of `qInitResources_InspectorBackendCommands()'
	qrc_InspectorBackendCommands.o:qrc_InspectorBackendCommands.cpp:(.text+0x40): first defined here
	/usr/local/share/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_InspectorBackendCommands.o): In function `qCleanupResources_InspectorBackendCommands()':
	qrc_InspectorBackendCommands.cpp:(.text._Z42qCleanupResources_InspectorBackendCommandsv+0x0): multiple definition of `qCleanupResources_InspectorBackendCommands()'
	qrc_InspectorBackendCommands.o:qrc_InspectorBackendCommands.cpp:(.text+0x90): first defined here
	collect2: error: ld returned 1 exit status
	make[1]: *** [../bin/phantomjs] Error 1
	make[1]: Leaving directory `/usr/local/share/phantomjs/src'
	make: *** [sub-src-phantomjs-pro-make_first-ordered] Error 2

How to fix this issue?

**Comment by designgrill** [comment]
Yup, the build still fails on ubuntu 14.04 for branch 2.0

```
Building main PhantomJS application...

cd src/ && ( test -e Makefile.phantomjs || /vol/ume01/phantomjs/src/qt/qtbase/bin/qmake /vol/ume01/phantomjs/src/phantomjs.pro -o Makefile.phantomjs ) && make -f Makefile.phantomjs 
make[1]: Entering directory `/vol/ume01/phantomjs/src'
g++ -Wl,-O1 -Wl,-rpath-link,/vol/ume01/phantomjs/src/qt/qtbase/lib -o ../bin/phantomjs phantom.o callback.o webpage.o webserver.o main.o utils.o networkaccessmanager.o cookiejar.o filesystem.o system.o env.o terminal.o encoding.o config.o childprocess.o repl.o crashdump.o mongoose.o linenoise.o utf8.o qcommandline.o minidump_file_writer.o convert_UTF.o md5.o string_conversion.o crash_generation_client.o exception_handler.o log.o linux_dumper.o linux_ptrace_dumper.o minidump_writer.o file_id.o guid_creator.o memory_mapped_file.o safe_readlink.o phantomjs_plugin_import.o qrc_phantomjs.o qrc_ghostdriver.o qrc_WebKit.o qrc_InspectorBackendCommands.o moc_phantom.o moc_callback.o moc_webpage.o moc_webserver.o moc_networkaccessmanager.o moc_cookiejar.o moc_filesystem.o moc_system.o moc_env.o moc_terminal.o moc_config.o moc_childprocess.o moc_repl.o moc_qcommandline.o   -L/vol/ume01/phantomjs/src/qt/qtbase/lib -lQt5WebKitWidgets -Wl,-whole-archive -Wl,-no-whole-archive -L/vol/ume01/phantomjs/src/qt/qtwebkit/Source/WebKit/release -Wl,-whole-archive -Wl,-no-whole-archive -L/vol/ume01/phantomjs/src/qt/qtwebkit/Source/WebCore/release -Wl,-whole-archive -Wl,-no-whole-archive -L/vol/ume01/phantomjs/src/qt/qtwebkit/Source/ThirdParty/leveldb/release -Wl,-whole-archive -Wl,-no-whole-archive -L/vol/ume01/phantomjs/src/qt/qtwebkit/Source/JavaScriptCore/release -Wl,-whole-archive -Wl,-no-whole-archive -L/vol/ume01/phantomjs/src/qt/qtwebkit/Source/WTF/release -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -Wl,-whole-archive -Wl,-no-whole-archive -lQt5PrintSupport -lQt5WebKit -Wl,-whole-archive -lWebKit1 -Wl,-no-whole-archive -Wl,-whole-archive -lWebCore -Wl,-no-whole-archive -Wl,-whole-archive -lleveldb -Wl,-no-whole-archive -Wl,-whole-archive -lJavaScriptCore -Wl,-no-whole-archive -Wl,-whole-archive -lWTF -Wl,-no-whole-archive -licudata -lQt5Sql -L/vol/ume01/phantomjs/src/qt/qtbase/plugins/accessible -lqtaccessiblewidgets -lQt5Widgets -L/vol/ume01/phantomjs/src/qt/qtbase/plugins/bearer -lqgenericbearer -lQt5Network -lssl -lcrypto -L/vol/ume01/phantomjs/src/qt/qtbase/plugins/platforms -lqphantom -lQt5PlatformSupport -lfontconfig -lfreetype -L/vol/ume01/phantomjs/src/qt/qtbase/plugins/imageformats -lqico -lQt5Gui -ljpeg -lpng -lqtharfbuzzng -lQt5Core -lz -licui18n -licuuc -lm -ldl -lrt -lpthread 
/vol/ume01/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_WebKit.o): In function `qInitResources_WebKit()':
qrc_WebKit.cpp:(.text._Z21qInitResources_WebKitv+0x0): multiple definition of `qInitResources_WebKit()'
qrc_WebKit.o:qrc_WebKit.cpp:(.text+0x0): first defined here
/vol/ume01/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_WebKit.o): In function `qCleanupResources_WebKit()':
qrc_WebKit.cpp:(.text._Z24qCleanupResources_WebKitv+0x0): multiple definition of `qCleanupResources_WebKit()'
qrc_WebKit.o:qrc_WebKit.cpp:(.text+0x30): first defined here
/vol/ume01/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_InspectorBackendCommands.o): In function `qInitResources_InspectorBackendCommands()':
qrc_InspectorBackendCommands.cpp:(.text._Z39qInitResources_InspectorBackendCommandsv+0x0): multiple definition of `qInitResources_InspectorBackendCommands()'
qrc_InspectorBackendCommands.o:qrc_InspectorBackendCommands.cpp:(.text+0x0): first defined here
/vol/ume01/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_InspectorBackendCommands.o): In function `qCleanupResources_InspectorBackendCommands()':
qrc_InspectorBackendCommands.cpp:(.text._Z42qCleanupResources_InspectorBackendCommandsv+0x0): multiple definition of `qCleanupResources_InspectorBackendCommands()'
qrc_InspectorBackendCommands.o:qrc_InspectorBackendCommands.cpp:(.text+0x30): first defined here
collect2: ld returned 1 exit status
make[1]: *** [../bin/phantomjs] Error 1
make[1]: Leaving directory `/vol/ume01/phantomjs/src'
make: *** [sub-src-phantomjs-pro-make_first-ordered] Error 2

```

**Comment by mdproductions** [comment]
Added a compiled binary for 15.10 if anyone interested: https://github.com/mdproductions/phantomjs/tree/master/bin/linux
