### ISSUE TITLE
function.bind() not working

### ISSUE THREAD

**Issue by masi** [ariya/phantomjs#13107]
var foobar = function() {
 // ...
}
foobar.bind(baz)

I get an error in PhantomJS 1.9.7 (Windows 7, 64bit):

TypeError: 'undefined' is not a function (evaluating 'foobar.bind()')

Seems to work in 2.0.0 though.

**Comment by Vitallium** [comment]
We're not going to fix it in 1.x version. Please, use PhantomJS.
