### ISSUE TITLE
Failed to build with Qt 5.8

### ISSUE THREAD

**Issue by yan12125** [ariya/phantomjs#14956]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
git-master

2. What steps will reproduce the problem?
  i. git clone https://github.com/ariya/phantomjs && cd phantomjs
  ii. qmake
  iii. make
There's a compilation error:
```
$ make
cd src/qt-qpa-platform-plugin/ && ( test -e Makefile.phantom || /usr/bin/qmake -o Makefile.phantom /home/yen/Projects/tmp/phantomjs/src/qt-qpa-platform-plugin/phantom.pro ) && make -f Makefile.phantom 
Info: creating stash file /home/yen/Projects/tmp/phantomjs/src/qt-qpa-platform-plugin/.qmake.stash
Project ERROR: Unknown module(s) in QT: platformsupport-private
make: *** [Makefile:44: sub--home-yen-Projects-tmp-phantomjs-src-qt-qpa-platform-plugin-phantom-pro-make_first-ordered] Error 3
```

3. Which operating system are you using?
Arch Linux

4. Did you use binary PhantomJS or did you compile it from source?
Compile it from source

5. Please provide any additional information below.
Latest Arch Linux ships with Qt 5.8. Apparently platformsupport-private is removed in Qt 5.8: http://stackoverflow.com/a/42198738/3786245

**Comment by tsviet** [comment]
I ask Vitaly about it. Qt5.8.0 file structure changed and not supported in phantomjs. You need qt5.7.1 and build webkit from annulen branch.

**Comment by yan12125** [comment]
Thanks. Is Qt 5.8 going to be supported in release 2.5? I see "Use system-installed Qt 5" is listed as a goal in #14458. As all other components on my system use Qt 5.8, it would be great to have PhantomJS running with it as well.

**Comment by yan12125** [comment]
FWIW, here are my changes for building PhantomJS against Qt 5.8:
```Diff
diff --git a/src/qt-qpa-platform-plugin/phantom.pri b/src/qt-qpa-platform-plugin/phantom.pri
index d8b2d115..29b7da89 100644
--- a/src/qt-qpa-platform-plugin/phantom.pri
+++ b/src/qt-qpa-platform-plugin/phantom.pri
@@ -1,4 +1,4 @@
-QT += core-private gui-private platformsupport-private
+QT += core-private gui-private fontdatabase_support_private eventdispatcher_support_private^M
 
 SOURCES += $$PWD/phantomintegration.cpp \
            $$PWD/phantombackingstore.cpp
diff --git a/src/qt-qpa-platform-plugin/phantomintegration.cpp b/src/qt-qpa-platform-plugin/phantomintegration.cpp
index 47e4b886..e74ea7e1 100644
--- a/src/qt-qpa-platform-plugin/phantomintegration.cpp
+++ b/src/qt-qpa-platform-plugin/phantomintegration.cpp
@@ -47,10 +47,10 @@
 #if defined(Q_OS_MAC)
 # include <QtPlatformSupport/private/qcoretextfontdatabase_p.h>
 #else
-# include <QtPlatformSupport/private/qgenericunixfontdatabase_p.h>
+# include <QtFontDatabaseSupport/private/qgenericunixfontdatabase_p.h>
 #endif
 
-#include <QtPlatformSupport/private/qgenericunixeventdispatcher_p.h>
+#include <QtEventDispatcherSupport/private/qgenericunixeventdispatcher_p.h>
 
 #include <qpa/qplatformnativeinterface.h>
 #include <qpa/qplatformscreen.h>

**Comment by kensoh** [comment]
If I understand correctly, there won't be a v2.5. But still believe and hope someone or company is stepping up to take over the baton from PhantomJS maintainer Vitaly.
