### ISSUE TITLE
Phantomjs 2.1.1 does not build on Ubuntu 16.04

### ISSUE THREAD

**Issue by salamani** [ariya/phantomjs#14530]
I wanted to build phantomjs version 2.1.1 on Ubuntu 16.04 for s390x architecture.

Steps to reproduce problem
  1. All packages suggested at http://phantomjs.org/build.html have been installed.
  2. Cloned phantomjs and git checkout 2.1.1
  3. python build.py

Last lines of error message
```
../../../include/QtCore/5.5.1/QtCore/private/../../../../../src/corelib/kernel/qvariant_p.h:293:   instantiated from 'static bool QVariantIsNull<Filter>::CallIsNull<T, IsAcceptedType>::isNull(const QVariant::Private*) [with T = QHash<QString, QVariant>, bool IsAcceptedType = true, Filter = <unnamed>::CoreTypesFilter]'
../../../include/QtCore/5.5.1/QtCore/private/../../../../../src/corelib/kernel/qvariant_p.h:312:   instantiated from 'bool QVariantIsNull<Filter>::delegate(const T*) [with T = QVariantHash, Filter = <unnamed>::CoreTypesFilter]'
../../../include/QtCore/5.5.1/QtCore/private/../../../../../src/corelib/kernel/qmetatypeswitcher_p.h:68:   instantiated from 'static ReturnType QMetaTypeSwitcher::switcher(DelegateObject&, int, const void*) [with ReturnType = bool, DelegateObject = QVariantIsNull<<unnamed>::CoreTypesFilter>]'
../../corelib/kernel/qvariant.cpp:129:   instantiated from here
../../../include/QtCore/5.5.1/QtCore/private/../../../../../src/corelib/kernel/qvariant_p.h:215: error: 'const struct QHash<QString, QVariant>' has no member named 'isNull'
make[2]: *** [.obj/qvariant.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/test/phantomjs/src/qt/qtbase/src/tools/bootstrap'
make[1]: *** [sub-bootstrap-make_first] Error 2
make[1]: Leaving directory `/home/test/phantomjs/src/qt/qtbase/src'
make: *** [sub-src-make_first] Error 2

ERROR: Failed to build PhantomJS! Building Qt Base failed.
```

**Comment by Vitallium** [comment]
Please report this bug to Qt bug tracker. This issue is not related to PhantomJS. Thanks!
