### ISSUE TITLE
PhantomJS 2 does not build on OS X 10.0 (Yosemite)

### ISSUE THREAD

**Issue by sikachu** [ariya/phantomjs#12630]
There're several warning along the way, but the error that fails the build was:

```
/Applications/Xcode-Beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -c -pipe -O2 -isysroot /Applications/Xcode-Beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.6 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_STATICPLUGIN -DQT_PLUGIN -DQT_PRINTSUPPORT_LIB -DQT_PLATFORMSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../../../../mkspecs/macx-clang -I. -I../../../../include/QtPrintSupport/5.3.0 -I../../../../include/QtPrintSupport/5.3.0/QtPrintSupport -I../../../../include -I../../../../include/QtPrintSupport -I../../../../include/QtWidgets/5.3.0 -I../../../../include/QtWidgets/5.3.0/QtWidgets -I../../../../include/QtPlatformSupport -I../../../../include/QtPlatformSupport/5.3.0 -I../../../../include/QtPlatformSupport/5.3.0/QtPlatformSupport -I../../../../include/QtWidgets -I../../../../include/QtGui/5.3.0 -I../../../../include/QtGui/5.3.0/QtGui -I../../../../include/QtCore/5.3.0 -I../../../../include/QtCore/5.3.0/QtCore -I../../../../include/QtGui -I../../../../include/QtCore -I.moc qcocoaapplicationdelegate.mm -o .obj/qcocoaapplicationdelegate.o
qcocoaapplicationdelegate.mm:127:28: error: cannot initialize a parameter of type 'id<NSFileManagerDelegate>' with an lvalue of type 'NSObject<NSApplicationDelegate> *'
        [NSApp setDelegate:reflectionDelegate];
                           ^~~~~~~~~~~~~~~~~~
/Applications/Xcode-Beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSFileManager.h:109:47: note: passing argument to parameter 'delegate' here
@property (assign) id <NSFileManagerDelegate> delegate NS_AVAILABLE(10_5, 2_0);
                                              ^
1 error generated.
```

Please see the full build log here: https://gist.github.com/sikachu/131b66a23010aad6b785

**Comment by lentan1029** [comment]
I managed to get phantomjs 2.0.0 to build on Yosemite 10.10.1 by editing src/qt/qtbase/src/plugins/platforms/cocoa/qcocoaapplicationdelegate.mm
```
- (void)dealloc
{
    sharedCocoaApplicationDelegate = nil;
    [dockMenu release];
    [qtMenuLoader release];
    if (reflectionDelegate) {
        [NSApp setDelegate:reflectionDelegate]; // replace this line with [[NSApplication sharedApplication] setDelegate:reflectionDelegate];
        [reflectionDelegate release];
    }
    [[NSNotificationCenter defaultCenter] removeObserver:self];

    [super dealloc];
}
```

taken from https://github.com/Homebrew/homebrew/issues/29837

**Comment by rdpanek** [comment]
@lentan1029 Good Job, your solution is functional.

**Comment by Aetherpoint** [comment]
Got the same errors on Yosemite 10.10.1 and worked through the wiki checks and @lentan1029's solution.

What's the final output when building supposed to be? Getting this at the end, and it's still reporting 1.9.8 with phantom.version.

```code

-L/Users/username/Repos/phantomjs/src/qt/qtbase/plugins/bearer -lqcorewlanbearer -framework CoreWLAN -lqgenericbearer -lQt5Network -lssl -lcrypto -L/Users/username/Repos/phantomjs/src/qt/qtbase/plugins/platforms -lqphantom -lQt5PlatformSupport -framework OpenGL -L/Users/username/Repos/phantomjs/src/qt/qtbase/plugins/imageformats -lqico -lQt5Gui -lqtharfbuzzng -lQt5Core -lz -lm

```

**Comment by rdpanek** [comment]
When will be this fix merged to 2.0 branch? Thanks

**Comment by eugene1g** [comment]
Thanks @lentan1029 for the pointer in the right direction. I applied your patch and compiled OSX/ubuntu/centos binaries for myself and others at https://github.com/eugene1g/phantomjs/releases

**Comment by mikemcquaid** [comment]
@lentan1029 @eugene1g Have either of you submitted a pull request to PhantomJS with this fix? No worries if not: I'm happy to do so.

**Comment by eugene1g** [comment]
Thanks for the reminder @mikemcquaid, just opened a pull request with the patch

**Comment by mikemcquaid** [comment]
@eugene1g :heart:

**Comment by paazmaya** [comment]
Would there be any reason why not update the included Qt 5.3.0 to the latest of 5.3 series when a new patch release comes out?

**Comment by Vitallium** [comment]
This #12578. We want to keep Qt git history separate from our history.

**Comment by bitwisor** [comment]
@lentan1029 got it right for **Yosemite 10.10.2**

**Comment by jywsn** [comment]
I can also confirm that @lentan1029 got it right for Yosemite 10.10.2

**Comment by tracer123** [comment]
@eugene1g Your solution worked perfectly. Thanks!

**Comment by kamote** [comment]
brew install phantomjs

**Comment by jancurn** [comment]
@antonioreyna I had the same problem when building PhantomJS 2 from sources on Mac OS X Yosemite. It was caused by left-over files from a previous build on Windows. `git clean -fx` fixed the problem.

**Comment by grzegorz-dubicki** [comment]
+1 @kamote - it just works

**Comment by mareknov** [comment]
@antonioreyna how did you solved compilation errors? I'm having the same problem on Yosemite 10.10.5, Xcode (both 6.4 and 7.0 beta 6) and none of the aforementioned solutions work for me.

**Comment by antonioreyna** [comment]
@mareknov hello, I downloaded a pre-compiled binary and I have been working with that without any problems so far, here is what i use in OSX, if you need it, I hope it helps you https://dl.dropboxusercontent.com/u/1011606/phantomjs-osx-2.zip

**Comment by mareknov** [comment]
@antonioreyna thanks for the binary. It works ok as well as installation through homebrew, but I wanted to compile it. On Ubuntu it works for me without any issues.

**Comment by antonioreyna** [comment]
@mareknov yes, i have it on debian and everything is ok too. Let us know if you find out a solution :) on Yosemite and I hope it works also on El Capitan.

**Comment by sebastianbochan** [comment]
+1 @kamote - it just works

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://emarketing-services.netsmartz.net/conservative.php?rxkor>

 

klaus@hebsgaard.dk
