### ISSUE TITLE
Release of PhantomJS 2.0.1

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#12902]
This is the first maintenance release after 2.0.0 designed to address immediate critical issues.

- [ ] Update ChangeLog
- [ ] Update web sites
- [ ] Upload source tarball
- [ ] Prepare OS X binary
- [ ] Prepare Windows binary
- [ ] Prepare Linux 64-bit binary
- [ ] Prepare Linux 32-bit binary

**Comment by polarathene** [comment]
I've not tested via Linux/OSX but has 2.0.0 taken on the scaling problems that Windows had prior to 2.0.0 on these platforms? See this [example/issue](https://github.com/ariya/phantomjs/issues/12936) with a detailed response from me on my own findings in [this comment](https://github.com/ariya/phantomjs/issues/12936#issuecomment-73174137). You can see that with 2.0.0 on OSX example image, the original content has been scaled up by 1/3rd converting it from 72px per inch to 96px per inch(CSS inch), if I'm not mistaken this is due to OSX being 72dpi? I'm not sure what changes with 2.0.0 caused this, but Windows now renders PDF perfectly, hopefully you can fix this issue asap :)

**Comment by mickaelandrieu** [comment]
@ariya any release date ? I'm thinking about prepare a release for CasperJS with phantomjs 2 support :)

**Comment by thomasbachem** [comment]
I think a regression like #12685 cannot wait for 2.1 and should instead be part of 2.0.1.

**Comment by benjaminwood** [comment]
I agree, #12685 is a dealbreaker for many of us. I'm excited to upgrade some projects to v2, but can't do it until this is resolved.

**Comment by floundies** [comment]
^ agreed. thanks for all the hard work.

**Comment by Vitallium** [comment]
Issues to fix before we release 2.0.1 version:
- [ ] Integrate the latest version of Ghostdriver
- [ ] #12506
- [ ] #12948
- [ ] #12900
- [ ] #12685

**Comment by mickaelandrieu** [comment]
@Vitallium Sorry to not have the skills for help (I don't know C++).
If I can do something to help you (like testing installation process on my linux mint 17) tell me :)

**Comment by LeMoussel** [comment]
@Vitallium Sorry itou 
I can help you to testing installation process & application on Windows 7 64 bits & 32bits.

**Comment by Vitallium** [comment]
FYI: I recently discovered that we have a Gitter chat for PhantomJS. You can catch me there.

**Comment by LeMoussel** [comment]
Is this Gitter chat : https://gitter.im/ ?

**Comment by Vitallium** [comment]
@LeMoussel yes.

**Comment by ngdaddikar** [comment]
Any news on 2.0.1 release?

**Comment by ronwsmith** [comment]
:+1:

**Comment by rovanalfarry** [comment]
:+1::+1::+1:

**Comment by davidwindell** [comment]
:-1: PDF's still not working on 2.x in Linux

**Comment by Vitallium** [comment]
@davidwindell issue?

**Comment by davidwindell** [comment]
@Vitallium #12685 (and it's associated dupes #13048 #12990, etc). Stuck on 1.x for now :(

**Comment by Vitallium** [comment]
@davidwindell this issue is in the block list for 2.0.1 :-)

**Comment by Friedel-Castor** [comment]
A nice to have is IMHO a fix for https://github.com/ariya/phantomjs/issues/10465# and an opportunity to repeat the table headers after a page break.

**Comment by alecl** [comment]
Pardon if I've misunderstood but given only #12506 seems to be the only regression from 2.0.0 that breaks people's test cases outright and a fix is already known for a few months I'm not sure why that can't be released as 2.0.1 (source + Windows / OS X binaries) and the others worked on for a separate release. Releasing often is a good thing.

**Comment by maokomioko** [comment]
@alecl :+1:

**Comment by mneumark** [comment]
@alecl Especially since I hear this update is requirement to get phantomjs working on 10.11 El Capitan.

**Comment by ngdaddikar** [comment]
I agree!

**Comment by MartinKoerner** [comment]
:+1:

**Comment by Vitallium** [comment]
I think I can publish nightly builds of PhantomJS 2.0.1 for all platforms. Since you guys want it (esp for El Capitan) :-)

**Comment by rrooding** [comment]
That would be great :)!

**Comment by Deradon** [comment]
:+1:

**Comment by alibojar** [comment]
:+1:

**Comment by alecl** [comment]
Would be much appreciated!

**Comment by jeantil** [comment]
As I understand it, building binaries for el capitan requires https://github.com/ariya/phantomjs/pull/13640 to be merged. It would be nice if that happened before 2.0.1 :)

**Comment by Vitallium** [comment]
@jeantil yes, 2.0.1 will support El Capitan.

**Comment by jeantil** [comment]
Nice ! Let us know if we can help :)

**Comment by jcrben** [comment]
With regard to #12506, it seems that the issue is reported upstream at https://bugreports.qt.io/browse/QTBUG-44237

**Comment by rajachawat** [comment]
Will 2.0.1 support TLSv1.2?

**Comment by MartinKoerner** [comment]
@Vitallium thx for the prerelease, but are you sure, it has all planned fixes for 2.0.1 included? I'm on El Capitan and running both into errors in Upload form and with strange "undefined is not an object" errors (which were there reason, we tried PhantomJS 2 in the first place)

The "inofficial" prerelease from July (found here https://github.com/skakri/phantomjs/releases/tag/2.0.1-regression-12506) solved these issues (on El Capitan, but not on Ubuntu).

I'm not sure if I should introduce a new bug report for this, because I fear it gets very confusion with different bugs for different "versions of 2.0.1"...

**Comment by brunowego** [comment]
:+1:

**Comment by Vitallium** [comment]
@MartinKoerner not all. This prerelease doesn't have two fixes.

**Comment by zhagnsz** [comment]
oh, It's important to me about fixed bug below;
1.Webpage.uploadFile not working in phantomjs 2.0 #12506
   https://github.com/ariya/phantomjs/issues/12506
2. PhantomJS 2 does not build on OS X 10.10 (Yosemite)
    https://github.com/ariya/phantomjs/issues/12928
     when i build phantomjs from sourcecode, i got some errors:
     a.error: "Feature _POSIX_TIMERS not available"
     b.error: use of undeclared identifier
     c.error: no member named 'posix_fallocate' in the global namespace
     d.error: no member named 'mremap' in the global namespace
     e.  error: use of undeclared identifier 'MREMAP_MAYMOVE'
     f.fatal error: 'sys/inotify.h' file not found
     g. fatal error: 'sys/eventfd.h' file not found
     ......
     i am very hurry,  please help to to fix first bug. thank you.......

**Comment by Vitallium** [comment]
@zhagnsz we have fixes for both issues. So, don't worry. They are included in the upcoming 2.0.1 release.

**Comment by zhagnsz** [comment]
@Vitallium  okay, thank you very much!  when are you going to update to the 2.0.1 version.....

**Comment by bcardiff** [comment]
+1 for a release of 2.0.1. We would really enjoy #12506 + El capitan support.

**Comment by fabn** [comment]
@Vitallium Any ETA for 2.0.1? Thanks.

**Comment by dbrans** [comment]
+1

**Comment by ariya** [comment]
We're low on manpower so we won't do 2.0.1 at all. We'll skip to 2.1 (follow #12970).
