### ISSUE TITLE
Can't build  with Centos 4.3 gcc 4.6

### ISSUE THREAD

**Issue by uoeye** [ariya/phantomjs#14370]
PhantomJS can't be build with Centos 4.3 gcc 4.6 anymore.

`
<srcbase> = /home/work/user/node/phantomjs/src/qt/qtbase 
<outbase> = /home/work/user/node/phantomjs/src/qt/qtbase 
Creating qmake...
.In file included from ../include/QtCore/qtypeinfo.h:1,
                 from ../include/QtCore/../../src/corelib/global/qglobal.h:1107,
                 from ../include/QtCore/qglobal.h:1,
                 from /home/work/user/node/phantomjs/src/qt/qtbase/qmake/library/qmake_global.h:37,
                 from /home/work/user/node/phantomjs/src/qt/qtbase/qmake/library/qmakeparser.h:37,
                 from /home/work/user/node/phantomjs/src/qt/qtbase/qmake/library/qmakeevaluator.h:41,
                 from /home/work/user/node/phantomjs/src/qt/qtbase/qmake/project.h:37,
                 from /home/work/user/node/phantomjs/src/qt/qtbase/qmake/project.cpp:34:
../include/QtCore/../../src/corelib/global/qtypeinfo.h:59: error:`is_enum' is not a member of `QtPrivate'
../include/QtCore/../../src/corelib/global/qtypeinfo.h:59: error: expected primary-expression before '>' token
../include/QtCore/../../src/corelib/global/qtypeinfo.h:59: error:`::value' has not been declared
In file included from ../include/QtCore/qmap.h:1,
                 from /home/work/user/node/phantomjs/src/qt/qtbase/qmake/library/qmakeevaluator.h:46,
                 from /home/work/user/node/phantomjs/src/qt/qtbase/qmake/project.h:37,
                 from /home/work/user/node/phantomjs/src/qt/qtbase/qmake/project.cpp:34:
../include/QtCore/../../src/corelib/tools/qmap.h:104: error: `template<class T> static typename QtPrivate::QEnableIf<(! QTypeInfo<T>::isComplex), void>::Type QMapNodeBase::callDestructorIfNecessary(T&)' and`template<class T> static typename QtPrivate::QEnableIf< QTypeInfo<T>::isComplex, void>::Type QMapNodeBase::callDestructorIfNecessary(T&)' cannot be overloaded
In file included from ../include/QtCore/qmetatype.h:1,
                 from ../include/QtCore/../../src/corelib/io/qfileinfo.h:40,
                 from ../include/QtCore/qfileinfo.h:1,
                 from ../include/QtCore/../../src/corelib/io/qdir.h:38,
                 from ../include/QtCore/qdir.h:1,
                 from /home/work/user/node/phantomjs/src/qt/qtbase/qmake/project.cpp:39:
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1637: error: `is_enum' is not a member of`QtPrivate'
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1637: error: expected primary-expression before '>' token
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1637: error: `::value' has not been declared
/home/work/user/node/phantomjs/src/qt/qtbase/qmake/project.cpp: In member function`bool QMakeProject::test(const ProKey&, const QList<ProStringList>&)':
/home/work/user/node/phantomjs/src/qt/qtbase/qmake/project.cpp:98: warning: ignoring return value of `QString QString::arg(const QString&, int, QChar) const', declared with attribute warn_unused_result
/home/work/user/node/phantomjs/src/qt/qtbase/qmake/project.cpp: In member function`QStringList QMakeProject::expand(const ProKey&, const QList<ProStringList>&)':
/home/work/user/node/phantomjs/src/qt/qtbase/qmake/project.cpp:120: warning: ignoring return value of `QString QString::arg(const QString&, int, QChar) const', declared with attribute warn_unused_result
/home/work/user/node/phantomjs/src/qt/qtbase/qmake/project.cpp: In member function`void QMakeProject::dump() const':
/home/work/user/node/phantomjs/src/qt/qtbase/qmake/project.cpp:161: warning: ignoring return value of `QByteArray QString::toLocal8Bit() const', declared with attribute warn_unused_result
../include/QtCore/../../src/corelib/kernel/qmetatype.h: At global scope:
../include/QtCore/../../src/corelib/kernel/qmetatype.h: In instantiation of`QtPrivate::QMetaTypeTypeFlagsQtMetaTypePrivate::QSequentialIterableImpl':
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1682:   instantiated from `int qRegisterNormalizedMetaType(const QByteArray&, T*, typename QtPrivate::MetaTypeDefinedHelper<T, ( QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType) [with T = QtMetaTypePrivate::QSequentialIterableImpl]'
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1717:   instantiated from`int qRegisterMetaType(const char_, T_, typename QtPrivate::MetaTypeDefinedHelper<T, ( QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType) [with T = QtMetaTypePrivate::QSequentialIterableImpl]'
../include/QtCore/../../src/corelib/kernel/qmetatype.h:2191:   instantiated from here
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1630: error: enumerator value for `Flags' not integer constant
../include/QtCore/../../src/corelib/kernel/qmetatype.h: In instantiation of`QtPrivate::QMetaTypeTypeFlagsQtMetaTypePrivate::QAssociativeIterableImpl':
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1682:   instantiated from `int qRegisterNormalizedMetaType(const QByteArray&, T*, typename QtPrivate::MetaTypeDefinedHelper<T, ( QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType) [with T = QtMetaTypePrivate::QAssociativeIterableImpl]'
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1717:   instantiated from`int qRegisterMetaType(const char_, T_, typename QtPrivate::MetaTypeDefinedHelper<T, ( QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType) [with T = QtMetaTypePrivate::QAssociativeIterableImpl]'
../include/QtCore/../../src/corelib/kernel/qmetatype.h:2192:   instantiated from here
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1630: error: enumerator value for `Flags' not integer constant
../include/QtCore/../../src/corelib/kernel/qmetatype.h: In instantiation of`QtPrivate::QMetaTypeTypeFlagsQtMetaTypePrivate::QPairVariantInterfaceImpl':
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1682:   instantiated from `int qRegisterNormalizedMetaType(const QByteArray&, T*, typename QtPrivate::MetaTypeDefinedHelper<T, ( QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType) [with T = QtMetaTypePrivate::QPairVariantInterfaceImpl]'
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1717:   instantiated from`int qRegisterMetaType(const char_, T_, typename QtPrivate::MetaTypeDefinedHelper<T, ( QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType) [with T = QtMetaTypePrivate::QPairVariantInterfaceImpl]'
../include/QtCore/../../src/corelib/kernel/qmetatype.h:2193:   instantiated from here
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1630: error: enumerator value for `Flags' not integer constant
../include/QtCore/../../src/corelib/kernel/qmetatype.h: In instantiation of`QtPrivate::QMetaTypeTypeFlags<QFileInfo>':
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1682:   instantiated from `int qRegisterNormalizedMetaType(const QByteArray&, T*, typename QtPrivate::MetaTypeDefinedHelper<T, ( QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType) [with T = QFileInfo]'
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1717:   instantiated from`int qRegisterMetaType(const char_, T_, typename QtPrivate::MetaTypeDefinedHelper<T, ( QMetaTypeId2<T>::Defined && (! QMetaTypeId2<T>::IsBuiltIn))>::DefinedType) [with T = QFileInfo]'
../include/QtCore/../../src/corelib/io/qfileinfo.h:150:   instantiated from here
../include/QtCore/../../src/corelib/kernel/qmetatype.h:1630: error: enumerator value for `Flags' not integer constant
gmake: **\* [project.o] Error 1

`
