### ISSUE TITLE
Can't build with XCode 7

### ISSUE THREAD

**Issue by Vitallium** [ariya/phantomjs#13607]
PhantomJS can't be build with XCode 7 anymore.

Apple removed OpenSSL headers in XCode 7 version. Build now fails with the following error:
```
openssl.cpp:34:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h>
```

**Comment by zackw** [comment]
"... unless you have OpenSSL installed via ports/homebrew," right?

Do newer versions of Qt know about Apple's replacement TLS library?  I can't really blame them for desupporting their ancient embedded copy of OpenSSL.

**Comment by Vitallium** [comment]
Yes, and you also need to pass additional arguments to the build script:
```
./build.sh --qtdeps=bundled --qt-config -L/usr/local/opt/openssl/lib --qt-config -I/usr/local/opt/openssl/include
```
I don't know what Qt will do with that. But I'll have a look to their bug tracker.

**Comment by Vitallium** [comment]
More errors with XCode 7, now in Webkit.
```
lalr.cpp:241:1: error: declaration of anonymous struct must be a definition
struct _Nullable: public std::unary_function<Name, bool>
^
lalr.cpp:241:56: error: expected unqualified-id
struct _Nullable: public std::unary_function<Name, bool>
                                                       ^
lalr.cpp:303:98: error: expected expression
          NameList::iterator nn = std::find_if (rule->rhs.begin (), rule->rhs.end (), std::not1 (_Nullable (this)));
                                                                                                 ^
lalr.cpp:638:107: error: expected expression
                  NameList::iterator first_not_nullable = std::find_if (dot, rule->rhs.end (), std::not1 (_Nullable (this)));
```

**Comment by zackw** [comment]
@Vitallium I have a Mac and I can poke at things if you need me to, but it's old and slow and hasn't been updated to El Capitan yet (and I would prefer to wait at least a few months before I do that).

**Comment by Vitallium** [comment]
@zackw don't worry. I got this!

**Comment by Vitallium** [comment]
Fixed in #13640

**Comment by karlingen** [comment]
go go @Vitallium !

**Comment by taf2** [comment]
Getting

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libQt5Test.a(qbenchmarkperfevents.o) has no symbols
```

**Comment by taf2** [comment]
removing --qtdeps=bundled  from the above suggestion and running:

 ./build.sh --qt-config -L/usr/local/opt/openssl/lib --qt-config -I/usr/local/opt/openssl/include

we get:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -headerpad_max_install_names -Wl,-dead_strip -stdlib=libstdc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -o ../../../bin/qdoc .obj/atom.o .obj/codechunk.o .obj/codemarker.o .obj/codeparser.o .obj/config.o .obj/cppcodemarker.o .obj/cppcodeparser.o .obj/ditaxmlgenerator.o .obj/doc.o .obj/editdistance.o .obj/generator.o .obj/helpprojectwriter.o .obj/htmlgenerator.o .obj/location.o .obj/main.o .obj/node.o .obj/openedlist.o .obj/plaincodemarker.o .obj/puredocparser.o .obj/qdocdatabase.o .obj/qdoctagfiles.o .obj/qdocindexfiles.o .obj/quoter.o .obj/separator.o .obj/text.o .obj/tokenizer.o .obj/tree.o .obj/yyindent.o .obj/qqmljsast.o .obj/qqmljsastvisitor.o .obj/qqmljsengine_p.o .obj/qqmljsgrammar.o .obj/qqmljslexer.o .obj/qqmljsparser.o .obj/jscodemarker.o .obj/qmlcodemarker.o .obj/qmlcodeparser.o .obj/qmlmarkupvisitor.o .obj/qmlvisitor.o   -L/usr/local/opt/openssl/lib -L/Users/taf2/work/phantomjs/src/qt/qtbase/lib -lQt5Xml -framework DiskArbitration -framework IOKit -framework ApplicationServices -framework CoreServices -framework CoreFoundation -framework Foundation -lQt5Core -lz -lm
ld: warning: direct access in QDomElementPrivate::save(QTextStream&, int, int) const to global weak symbol QHash<QString, QHashDummyValue>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, QHashDummyValue>::insert(QString const&, QHashDummyValue const&) to global weak symbol QHash<QString, QHashDummyValue>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, QHashDummyValue>::insert(QString const&, QHashDummyValue const&) to global weak symbol QHash<QString, QHashDummyValue>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, QHashDummyValue>::insert(QString const&, QHashDummyValue const&) to global weak symbol QHash<QString, QHashDummyValue>::duplicateNode(QHashData::Node*, void*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QXmlSimpleReaderPrivate::~QXmlSimpleReaderPrivate() to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QXmlSimpleReaderPrivate::~QXmlSimpleReaderPrivate() to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QXmlSimpleReader::parse(QXmlInputSource const*, bool) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QXmlSimpleReader::parse(QXmlInputSource const*, bool) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QXmlSimpleReaderPrivate::isExpandedEntityValueTooLarge(QString*) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QXmlSimpleReaderPrivate::isExpandedEntityValueTooLarge(QString*) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QXmlSimpleReaderPrivate::isExpandedEntityValueTooLarge(QString*) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QXmlSimpleReaderPrivate::isExpandedEntityValueTooLarge(QString*) to global weak symbol QHash<QString, int>::duplicateNode(QHashData::Node*, void*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QXmlSimpleReaderPrivate::isExpandedEntityValueTooLarge(QString*) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QXmlSimpleReaderPrivate::isExpandedEntityValueTooLarge(QString*) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QXmlSimpleReaderPrivate::isExpandedEntityValueTooLarge(QString*) to global weak symbol QHash<QString, int>::duplicateNode(QHashData::Node*, void*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, QHash<QString, int> >::operator[](QString const&) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, QHash<QString, int> >::operator[](QString const&) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, QHash<QString, int> >::operator[](QString const&) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, QHash<QString, int> >::operator[](QString const&) to global weak symbol QHash<QString, int>::duplicateNode(QHashData::Node*, void*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, int>::operator[](QString const&) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, int>::operator[](QString const&) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, int>::operator[](QString const&) to global weak symbol QHash<QString, int>::duplicateNode(QHashData::Node*, void*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, QHash<QString, int> >::deleteNode2(QHashData::Node*) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, int>::operator=(QHash<QString, int> const&) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, int>::operator=(QHash<QString, int> const&) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, int>::operator=(QHash<QString, int> const&) to global weak symbol QHash<QString, int>::duplicateNode(QHashData::Node*, void*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, int>::operator=(QHash<QString, int> const&) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, QHash<QString, int> >::duplicateNode(QHashData::Node*, void*) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, QHash<QString, int> >::duplicateNode(QHashData::Node*, void*) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, QHash<QString, int> >::duplicateNode(QHashData::Node*, void*) to global weak symbol QHash<QString, int>::duplicateNode(QHashData::Node*, void*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QCommandLineParser::values(QString const&) const to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QCommandLineParser::values(QString const&) const to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QCommandLineParser::values(QString const&) const to global weak symbol QHash<QString, int>::duplicateNode(QHashData::Node*, void*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, int>::insert(QString const&, int const&) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, int>::insert(QString const&, int const&) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, int>::insert(QString const&, int const&) to global weak symbol QHash<QString, int>::duplicateNode(QHashData::Node*, void*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, int>::find(QString const&) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, int>::find(QString const&) to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QHash<QString, int>::find(QString const&) to global weak symbol QHash<QString, int>::duplicateNode(QHashData::Node*, void*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QCommandLineParserPrivate::~QCommandLineParserPrivate() to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QCommandLineParserPrivate::~QCommandLineParserPrivate() to global weak symbol QHash<QString, int>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QtPrivate::QStringList_removeDuplicates(QStringList*) to global weak symbol QHash<QString, QHashDummyValue>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QtPrivate::QStringList_removeDuplicates(QStringList*) to global weak symbol QHash<QString, QHashDummyValue>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QtPrivate::QStringList_removeDuplicates(QStringList*) to global weak symbol QHash<QString, QHashDummyValue>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QtPrivate::QStringList_removeDuplicates(QStringList*) to global weak symbol QHash<QString, QHashDummyValue>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QtPrivate::QStringList_removeDuplicates(QStringList*) to global weak symbol QHash<QString, QHashDummyValue>::duplicateNode(QHashData::Node*, void*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QDirIteratorPrivate::QDirIteratorPrivate(QFileSystemEntry const&, QStringList const&, QFlags<QDir::Filter>, QFlags<QDirIterator::IteratorFlag>, bool) to global weak symbol QHash<QString, QHashDummyValue>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QDirIteratorPrivate::~QDirIteratorPrivate() to global weak symbol QHash<QString, QHashDummyValue>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QResourcePrivate::ensureChildren() const to global weak symbol QHash<QString, QHashDummyValue>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in QResourcePrivate::ensureChildren() const to global weak symbol QHash<QString, QHashDummyValue>::deleteNode2(QHashData::Node*) means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
make: *** [sub-src-make_first] Error 2
```

**Comment by Vitallium** [comment]
Don't remove `qtdeps=bundled`. And do a clean build. Run `git clean -dfxq` to remove all artifacts.
Or just grab the compiled version from here: https://github.com/Vitallium/phantomjs/releases/tag/2.0.1

**Comment by taf2** [comment]
Did this and now we're setting the following:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libQt5Network.a(qnetworkaccessdebugpipebackend.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libQt5Network.a(moc_qnetworkaccessdebugpipebackend_p.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libQt5Network.a(moc_qsslsocket_openssl_p.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s libQt5Network.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libQt5Network.a(qnetworkaccessdebugpipebackend.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libQt5Network.a(moc_qnetworkaccessdebugpipebackend_p.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libQt5Network.a(moc_qsslsocket_openssl_p.o) has no symbols
rm -f ../../lib/libQt5Network.a
mv -f libQt5Network.a ../../lib/
2 warnings generated.
rm -f libQt5Sql.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq libQt5Sql.a .obj/qsqlquery.o .obj/qsqldatabase.o .obj/qsqlfield.o .obj/qsqlrecord.o .obj/qsqldriver.o .obj/qsqldriverplugin.o .obj/qsqlerror.o .obj/qsqlresult.o .obj/qsqlindex.o .obj/qsqlcachedresult.o .obj/qsql_sqlite.o .obj/sqlite3.o .obj/qsqlquerymodel.o .obj/qsqltablemodel.o .obj/qsqlrelationaldelegate.o .obj/qsqlrelationaltablemodel.o .obj/moc_qsqldriver.o .obj/moc_qsqldriverplugin.o .obj/moc_qsql_sqlite_p.o .obj/moc_qsqlquerymodel.o .obj/moc_qsqltablemodel.o .obj/moc_qsqlrelationaltablemodel.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libQt5Sql.a(qsqlrelationaldelegate.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s libQt5Sql.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libQt5Sql.a(qsqlrelationaldelegate.o) has no symbols
rm -f ../../lib/libQt5Sql.a
mv -f libQt5Sql.a ../../lib/
make: *** [sub-src-make_first] Error 2
```

**Comment by Vitallium** [comment]
Post the full build (or just do the build again to receive errors)

**Comment by brunowego** [comment]
I think this issue is like my issue:

```
brew install phantomjs --HEAD                                                                                                                   7:07:07  ☁  develop ☂ 𝝙 ⚡ ✭ 𝝙
==> Cloning https://github.com/ariya/phantomjs.git
Updating /Library/Caches/Homebrew/phantomjs--git
==> Checking out branch master
==> ./build.sh --confirm --jobs 8 --qt-config -openssl-linked
Last 15 lines from /Users/Bruno/Library/Logs/Homebrew/phantomjs/01.build.sh:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE  -I. -I../../../mkspecs/macx-clang -o getifaddrs.o getifaddrs.cpp
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -o getifaddrs getifaddrs.o
getifaddrs enabled.
OpenSSL auto-detection... ()
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -DQT_NO_GRAPHICSVIEW -DQT_NO_GRAPHICSEFFECT -DQT_NO_STYLESHEET -DQT_NO_STYLE_CDE -DQT_NO_STYLE_CLEANLOOKS -DQT_NO_STYLE_MOTIF -DQT_NO_STYLE_PLASTIQUE -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE  -I. -I../../../mkspecs/macx-clang -o openssl.o openssl.cpp
openssl.cpp:34:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h>
         ^
1 error generated.
make: *** [openssl.o] Error 1
OpenSSL disabled.
OpenSSL support cannot be enabled due to functionality tests!
 Turn on verbose messaging (-v) to /private/tmp/phantomjs20151105-80800-hgq4z4/src/qt/qtbase/configure to see the final report.
 If you believe this message is in error you may use the continue
 switch (-continue) to /private/tmp/phantomjs20151105-80800-hgq4z4/src/qt/qtbase/configure to continue.

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Update phantomjs.rb https://github.com/Homebrew/homebrew/pull/45656
Phantomjs 2.0 fails to install on 10.11 https://github.com/Homebrew/homebrew/issues/42249
Phantomjs fails to build on 10.6 https://github.com/Homebrew/homebrew/issues/38916
```

**Comment by jeantil** [comment]
@brunowego if I read this correctly it tries to build from ariya's master which doesn't include https://github.com/ariya/phantomjs/pull/13640 and therefore doesn't have the fix for the build. 
As long as the pull request is not merged building from master will not work. 

@Vitallium did I get this right ? can you tell us what is blocking 13640 (it has been out there for a while now) and if we can do something to help ?

**Comment by Vitallium** [comment]
@jeantil yes, that's correct. To merge #13640 I need "Ok" responses from all contributors. Because there are breaking changes in my pull request.

**Comment by brunowego** [comment]
Thanks @jeantil :+1:

**Comment by jeantil** [comment]
@Vitallium thanks for the update :) (sadly I have yet to see a single OK from any other contributor on the PR after 2 weeks :/ )

**Comment by Vitallium** [comment]
Fixed in master. (see https://github.com/ariya/phantomjs/commit/2846f07bf46b0b1221c459be8278b456eee1b6b2)

**Comment by astefanutti** [comment]
Since the Qt 5.5.1 upgrade, I get the following error message when compiling on Mac OS X:
```
QtWebKit: created version header
QtWebKit: created master header
QtWebKit: created headers.pri file
rm -f libQt5WebKit.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq libQt5WebKit.a 
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make[2]: *** [/Users/astefanu/Development/phantomjs-ariya/src/qt/qtbase/lib/libQt5WebKit.a] Error 1
make[1]: *** [sub-api-pri-make_first-ordered] Error 2
make: *** [sub-Source-QtWebKit-pro-make_first-ordered] Error 2

ERROR: Failed to build PhantomJS! Building Qt WebKit failed.
```

**Comment by Vitallium** [comment]
@astefanutti yeah, the upgrade to Qt 5.5.1 did break the QtWebkit build. I'm working on this. Don't worry :)

**Comment by astefanutti** [comment]
@Vitallium ok, thanks for update.

**Comment by Vitallium** [comment]
@astefanutti just pushed the update.

**Comment by astefanutti** [comment]
@Vitallium thanks for the heads up. Compilation works fine, unfortunately I get the following error message when executing the produced binary: 
```
This application failed to start because it could not find or load the Qt platform plugin "phantom".

Reinstalling the application may fix this problem.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Abort trap: 6
```
Is that a known issue?

**Comment by Vitallium** [comment]
I wonder if this commit https://github.com/ariya/phantomjs/commit/287ed91c22b91e5284f1a122d92e56cbb6cedf9a introduces this behaviour.

**Comment by Vitallium** [comment]
@astefanutti done!

**Comment by astefanutti** [comment]
@Vitallium that works like a charm. Thanks for the faster than lightning fixes!

**Comment by generalconsensus** [comment]
I am seeing that Xcode 7.2, Homebrew Openssl and PhantomJS are not able to determine the target architecture:

![phantomjs_build](https://cloud.githubusercontent.com/assets/1254782/12491047/b361fc5a-c02d-11e5-9d5f-762eeece52ad.gif)

**Comment by mepard** [comment]
I'm not having any problem building with Xcode 7.2.  I just say

 ./build.py --confirm --debug      (or --release)

You might try cleaning the qts:

./build.py --confirm --debug --git-clean-qtbase --git-clean-qtwebkit

**Comment by generalconsensus** [comment]
perfect, thanks @mepard. The second clean qts appears to be working
